name: bone-enhance
channels:
  - pytorch
  - defaults
dependencies:
#  - cudatoolkit==10.2
#  - collagen
  - dill
  - h5py
  - matplotlib
  - numpy
  - numba
  - opencv
  - pandas
  - pyyaml
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools
  - tqdm
  - pytorch
