name: bone-super-resolution
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - pip=20.1.1=py37_1
  - pip:
    - git+https://github.com/MIPT-Oulu/Collagen.git@collagen-super-resolution
    - git+https://github.com/imedslab/solt.git
    - deep-pipeline==0.2.5
    - h5py==2.10.0
    - omegaconf==2.0.0
    - opencv-python==4.3.0.38
    - pillow==6.1.0
    - pretrainedmodels==0.7.4
    - pydicom
    - pytorch-toolbelt==0.3.2
    - segmentation-models-pytorch==0.1.0
    - solt==0.1.9
    - tensorboard==2.3.0
    - tensorboardx==2.1
    - termcolor==1.1.0
    - torchcontrib==0.0.2
    - torchfile==0.1.0
    - torchnet==0.0.4
    - torchvision==0.7.0
    - vtk==9.0.1
    - cloudpickle==1.5.0
    - cudatoolkit==10.1.243
    - dill==0.3.2
    - jupyter==1.0.0
    - matplotlib==3.2.2
    - matplotlib-base==3.2.2
    - numba==0.50.1
    - numpy==2.0.0
    - numpy-base==2.0.0
    - opencv==3.4.2
    - openpyxl==3.0.5
    - pandas==1.0.5
    - pip==20.1.1
    - py-opencv==3.4.2
    - python==3.7.7
    - pytorch==1.7.1
    - pyyaml==5.3.1
    - scikit-image==0.17.2
    - scikit-learn==0.23.1
    - scipy==1.5.0
    - setuptools==49.2.0
    - tensorboard-plugin-wit==1.6.0
    - tifffile==2020.12.8
    - tqdm==4.47.0
    - yaml==0.2.5
